config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :products, only: %i[index show]
  post 'cart/add_line_item', to: 'cart#add_line_item'
  get '/cart', to: 'cart#index'
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord  
  validates :total, presence: true
  validates :total, numericality: {
    greater_than: 0
  }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :price, presence: true
  validates :code, presence: true
  validates :price, numericality: {
    greater_than: 0
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_line_item
    result = Cart::Operation::AddToCart.call(params: params, session: session)
    @message = result.success? ? result[:success_message] : 'Something went wrong'
    redirect_to cart_path
  end

  def index
    result = Cart::Operation::GetLineItems.call(session: session)
    @line_items = result[:line_items]
    @total = result[:total]
    @count_cart = result[:count_cart]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @count_cart = session[:cart].nil? ? 0 : session[:cart].map { |_k, v| v }.sum
    run Product::Operation::Index do |ctx|
      @products = ctx[:model]
      @total = @model.count

      render
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/cart/index.haml
= render "shared/header", count_cart: @count_cart

.container
  .row.mb-4
    .col
      %h1.h5
        Cart Details
  .row
    .col-8
      - @line_items.each do |product, q|
        .row.mb-3
          .col-md-12.col-lg-12.col-sm-12.col-xs-12
            .card
              .row 
                .col-md-3
                  = image_tag "#{product.code}.jpeg", class: "card-img-top"
                .col-md-9
                  .card-body
                    .row 
                      .col-md-6
                        %h5.card-title
                          = product.name
                        %p.card-text
                          = product.code
                      .col-md-2
                        %p.card-text
                          €
                          = product.price
                      .col-md-2 
                        x 
                        = q
    .col-4
      .card
        .card-body
          %h5.card-title
            Total
          %p.card-text
            €
            = @total

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashRegister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css">
  </head>

  <body>
    <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js"></script>
  </body>
</html>

app/views/products/index.haml
= render "shared/header", count_cart: @count_cart

.container
  -# banner 
  .row.mb-4
    .col
      %h1.h3
        Welcome to our Amenitiz Coffee
  .row 
    .col
  .row
    .col 
      %h1.h6
        Special menu for you

  .row 
    - @products.each do |product|
      .col-md-4.col-lg-4.col-sm-6.col-xs-12
        .card
          = image_tag "#{product.code}.jpeg", class: "card-img-top"
          .card-body
            %h5.card-title
              = product.name
            %p.card-text
              = product.code
            %p.card-text
              €
              = product.price
            = link_to "Add to cart", cart_add_line_item_path(product_id: product.id), method: :post, local: false, class: "btn btn-primary",  data: { turbo_method: :post } 

app/views/shared/_header.haml
%header
  .container 
    .row 
      .col-md-3.col-lg-3.col-sm-4.col-xs-12
        = link_to image_tag("logo-amenitiz.svg", alt: "Logo", class: "logo", width: 200), root_path
      .col-md-7.col-lg-8.col-sm-5.col-xs-12
        %nav.navbar.navbar-expand-lg.align-items-lg-end
          .container-fluid
            .collapse.navbar-collapse.justify-content-end
              %ul.navbar-nav.mb-2.mb-lg-0
                %li.nav-item
                  = link_to "Home", root_path, class: 'nav-link'
                %li
                  = link_to "About", root_path, class: 'nav-link' #about_path
                %li
                  = link_to "Contact", root_path, class: 'nav-link' #contact_path
      .col-md-2.col-lg-1.col-sm-3.col-xs-12.align-self-center.text-end
        = link_to "Cart" do 
          = image_tag "cart.png", alt: "Cart", class: "cart", width: 30
          %small.count_cart
            = count_cart